name: Shapes Area Calculator

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-area-calculator:
    name: Test area calculator
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
     
      - name: Install dependencies
        run: yarn test
